# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ignasi Garcia Font
tagline:          ''
url:              http://ignasigarcia.com

author:
  name:           'Ignasi Garcia Font'
  url:            https://twitter.com/igarciafont

paginate:         1000

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/ignasigarcia

excerpt_separator: <!--more-->
